const $ = selector => document.querySelector(selector);
const gradePoints = { 'A':4, 'A-':3.7, 'B+':3.3, 'B':3, 'B-':2.7, 'C+':2.3, 'C':2, 'C-':1.7, 'D+':1.3, 'D':1, 'F':0 };
const dayOrder = {'الأحد':0,'الاثنين':1,'الثلاثاء':2,'الأربعاء':3,'الخميس':4};
const read = (key, fallback) => { try { return JSON.parse(localStorage.getItem(key)) ?? fallback; } catch { return fallback; } };
const save = (key, value) => localStorage.setItem(key,JSON.stringify(value));
const escapeHTML = value => String(value ?? '').replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]));

function addGpaRow(course='',credits=3,grade='A') { const row=document.createElement('div');row.className='gpa-row';row.innerHTML=`<input class="gpa-course" maxlength="30" value="${escapeHTML(course)}" placeholder="رمز المادة"><input class="gpa-credits" type="number" min="1" max="12" value="${credits}" aria-label="الساعات"><select class="gpa-grade" aria-label="التقدير">${Object.keys(gradePoints).map(item=>`<option${item===grade?' selected':''}>${item}</option>`).join('')}</select><button type="button" class="remove-row" aria-label="حذف">×</button>`; $('#gpaRows').append(row); row.querySelectorAll('input,select').forEach(input=>input.addEventListener('input',calculateGpa));row.querySelector('.remove-row').onclick=()=>{row.remove();calculateGpa();}; }
function calculateGpa(){const rows=[...document.querySelectorAll('.gpa-row')];let quality=0,credits=0;rows.forEach(row=>{const c=Number(row.querySelector('.gpa-credits').value)||0;const g=gradePoints[row.querySelector('.gpa-grade').value]??0;quality+=c*g;credits+=c;});$('#gpaResult').innerHTML=credits?`<strong>${(quality/credits).toFixed(2)} / 4.00</strong><span>معدل متوقع بناءً على ${credits} ساعة.</span>`:'أضف موادك لمعرفة المعدل المتوقع.';updateGraduation();}
function updateGraduation(){const required=Number($('#requiredCredits').value)||0,completed=Number($('#completedCredits').value)||0,gpa=Number($('#currentGpa').value)||0,remaining=Math.max(0,required-completed);$('#graduationResult').innerHTML=required?`<strong>باقي ${remaining} ساعة</strong><span>أنجزت ${completed} من ${required} ساعة · معدلك الحالي ${gpa.toFixed(2)}.</span>`:'أدخل بياناتك لرؤية الطريق المتبقي.';}
function renderAttendance(){const items=read('anjazAttendance',[]);$('#attendanceList').innerHTML=items.length?items.map((item,index)=>{const percent=(item.absent/item.total)*100;const danger=percent>=item.limit;return `<article class="compact-item ${danger?'is-danger':''}"><div><strong>${escapeHTML(item.course)}</strong><small>غياب ${item.absent}/${item.total} · ${percent.toFixed(1)}%</small></div><span>${danger?'تنبيه':'آمن'}</span><button data-attendance-remove="${index}" type="button">×</button></article>`;}).join(''):'<p class="empty">لم تضف أي مادة بعد.</p>';document.querySelectorAll('[data-attendance-remove]').forEach(button=>button.onclick=()=>{const items=read('anjazAttendance',[]);items.splice(Number(button.dataset.attendanceRemove),1);save('anjazAttendance',items);renderAttendance();});}
function time(value){const [h,m]=value.split(':').map(Number);return h*60+m;}
function renderRegistration(){const items=read('anjazRegistration',[]).sort((a,b)=>dayOrder[a.day]-dayOrder[b.day]||a.start.localeCompare(b.start));$('#registrationList').innerHTML=items.length?items.map((item,index)=>`<article class="compact-item"><div><strong>${escapeHTML(item.course)}</strong><small>${escapeHTML(item.day)} · ${item.start}–${item.end}</small></div><button data-registration-remove="${index}" type="button">×</button></article>`).join(''):'<p class="empty">أضف شعبك للتحقق من التعارض.</p>';document.querySelectorAll('[data-registration-remove]').forEach(button=>button.onclick=()=>{const items=read('anjazRegistration',[]).sort((a,b)=>dayOrder[a.day]-dayOrder[b.day]||a.start.localeCompare(b.start));items.splice(Number(button.dataset.registrationRemove),1);save('anjazRegistration',items);renderRegistration();});}

$('#addGpaRow').onclick=()=>addGpaRow();
for(let i=0;i<4;i++)addGpaRow();calculateGpa();
['requiredCredits','completedCredits','currentGpa'].forEach(id=>$('#'+id).addEventListener('input',updateGraduation));
$('#attendanceForm').addEventListener('submit',event=>{event.preventDefault();const items=read('anjazAttendance',[]);items.push({course:$('#attendanceCourse').value.trim(),total:Number($('#attendanceTotal').value),absent:Number($('#attendanceAbsent').value),limit:Number($('#attendanceLimit').value)});save('anjazAttendance',items);event.currentTarget.reset();$('#attendanceLimit').value=25;renderAttendance();});
$('#registrationForm').addEventListener('submit',event=>{event.preventDefault();const item={course:$('#registrationCourse').value.trim(),day:$('#registrationDay').value,start:$('#registrationStart').value,end:$('#registrationEnd').value};if(time(item.start)>=time(item.end)){alert('وقت النهاية يجب أن يكون بعد البداية.');return;}const items=read('anjazRegistration',[]);const conflict=items.find(existing=>existing.day===item.day&&time(item.start)<time(existing.end)&&time(existing.start)<time(item.end));if(conflict&&!confirm(`يوجد تعارض مع ${conflict.course}. هل تريد الإضافة؟`))return;items.push(item);save('anjazRegistration',items);event.currentTarget.reset();renderRegistration();});
renderAttendance();renderRegistration();
