const scheduleItems=(()=>{try{const saved=JSON.parse(localStorage.getItem('anjazSchedule')||'[]');return Array.isArray(saved)?saved:[];}catch{return [];}})();
const dayOrder={'الأحد':0,'الاثنين':1,'الثلاثاء':2,'الأربعاء':3,'الخميس':4};
const toMinutes=t=>{if(!t)return null;const[h,m]=t.split(':').map(Number);return h*60+m};
const overlap=(a1,a2,b1,b2)=>a1<b2&&b1<a2;
const escapeHTML=value=>String(value??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const saveSchedule=()=>localStorage.setItem('anjazSchedule',JSON.stringify(scheduleItems));
function findConflicts(){const out=[];for(let i=0;i<scheduleItems.length;i++)for(let j=i+1;j<scheduleItems.length;j++){const a=scheduleItems[i],b=scheduleItems[j];if(a.day===b.day&&overlap(toMinutes(a.lectureStart),toMinutes(a.lectureEnd),toMinutes(b.lectureStart),toMinutes(b.lectureEnd)))out.push(`تعارض محاضرات بين ${a.code} و${b.code} يوم ${a.day}`);if(a.finalDate&&b.finalDate&&a.finalDate===b.finalDate&&a.finalStart&&b.finalStart&&overlap(toMinutes(a.finalStart),toMinutes(a.finalEnd),toMinutes(b.finalStart),toMinutes(b.finalEnd)))out.push(`تعارض اختبارات نهائية بين ${a.code} و${b.code} بتاريخ ${a.finalDate}`);}return out;}
function renderSchedule(){const list=document.querySelector('#scheduleList'),alertBox=document.querySelector('#scheduleAlert');saveSchedule();if(!scheduleItems.length){list.innerHTML='<p class="empty">لم تُضف أي مادة بعد.</p>';alertBox.hidden=true;return;}const sorted=[...scheduleItems].sort((a,b)=>dayOrder[a.day]-dayOrder[b.day]||a.lectureStart.localeCompare(b.lectureStart));list.innerHTML=sorted.map(x=>`<article class="schedule-item"><div><strong>${escapeHTML(x.course)}</strong><span>${escapeHTML(x.code)}</span></div><p>${escapeHTML(x.day)} · ${escapeHTML(x.lectureStart)}–${escapeHTML(x.lectureEnd)}</p><small>${x.finalDate?`الاختبار النهائي: ${escapeHTML(x.finalDate)} · ${escapeHTML(x.finalStart||'—')}–${escapeHTML(x.finalEnd||'—')}`:'لم يُضف موعد الاختبار النهائي'}</small><button type="button" data-remove="${scheduleItems.indexOf(x)}">حذف</button></article>`).join('');document.querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>{scheduleItems.splice(Number(b.dataset.remove),1);renderSchedule()});const conflicts=findConflicts();if(conflicts.length){alertBox.hidden=false;alertBox.className='schedule-alert error';alertBox.innerHTML=`<strong>هناك تعارض في الجدول</strong><ul>${conflicts.map(c=>`<li>${escapeHTML(c)}</li>`).join('')}</ul>`;}else{alertBox.hidden=false;alertBox.className='schedule-alert success';alertBox.innerHTML='<strong>لا توجد تعارضات في الجدول الحالي.</strong>';}}
document.querySelector('#scheduleForm')?.addEventListener('submit',e=>{e.preventDefault();const item={course:document.querySelector('#scheduleCourse').value.trim(),code:document.querySelector('#scheduleCode').value.trim(),day:document.querySelector('#lectureDay').value,lectureStart:document.querySelector('#lectureStart').value,lectureEnd:document.querySelector('#lectureEnd').value,finalDate:document.querySelector('#finalDate').value,finalStart:document.querySelector('#finalStart').value,finalEnd:document.querySelector('#finalEnd').value};if(toMinutes(item.lectureStart)>=toMinutes(item.lectureEnd)){alert('وقت نهاية المحاضرة يجب أن يكون بعد وقت البداية.');return;}if(item.finalDate&&(item.finalStart||item.finalEnd)&&(!item.finalStart||!item.finalEnd||toMinutes(item.finalStart)>=toMinutes(item.finalEnd))){alert('أدخل وقت الاختبار النهائي بشكل صحيح.');return;}scheduleItems.push(item);e.target.reset();renderSchedule();});
document.querySelector('#clearSchedule')?.addEventListener('click',()=>{if(confirm('هل تريد مسح جميع المواد؟')){scheduleItems.length=0;renderSchedule();}});
renderSchedule();
